import 'dart:async';

import 'package:counter/models/count.dart';
import 'package:counter/models/counter.dart';
import 'package:counter/models/folder.dart';
import 'package:counter/models/reorder_item.dart';
import 'package:counter/models/settings.dart';
import 'package:counter/models/sorting_options.dart';
import 'package:counter/models/statistics.dart';

abstract interface class CounterRepository {
  bool isInitialized();
  Future<bool> initialize();
  Future<bool> resetCounterById(int counterId);
  Future<bool> incrementCounterById(int counterId, {value = 1});
  Future<bool> decrementCounterById(int counterId, {value = 1});
  Future<Counter> createCounter(Counter counter);
  Future<Counter> updateCounter(Counter counter);
  Future<bool> deleteCounterById(int counterId);
  Future<Counter> getCounterById(int counterId);
  Future<Counter?> getLastModifiedCounter(int folderId);
  Future<List<Counter>> getCountersByFolderId(int folderId);
  Future<List<Counter>> getCountersByFolderIdSorted(int folderId, SortingOptions? counterSorting);
  Future<List<Counter>> getAllCounters();
  Future<List<Counter>> getAllCountersToSynchronize();
  Future<List<int>> getAllDeletedCounterIdsToSynchronize();
  Future<bool> updateCountersSynchronizationTimestamp(List<int> counterIds);
  Future<bool> updateCountersSynchronizationTimestampByFolderId(int folderId);
  Future<bool> updateDeletedCountersSynchronizationTimestamp(List<int> counterIds);
  Future<bool> synchronizeCountersCount(int folderId);
  Future<List<Count>> getCountsByFolderId(int folderId);
  Future<List<Folder>> getAllFolders();
  Future<List<Folder>> getAllFoldersToSynchronize();
  Future<List<int>> getAllDeletedFolderIdsToSynchronize();
  Future<bool> updateFoldersSynchronizationTimestamp(List<int> folderIds);
  Future<bool> updateDeletedFoldersSynchronizationTimestamp(List<int> folderIds);
  Future<List<Folder>> getAllFoldersSorted(SortingOptions? sortingOptions);
  Future<Folder> createFolder(String folderName);
  Future<Folder> renameFolder(int folderId, String folderName);
  Future<Folder> getFolderById(int folderId);
  Future<bool> deleteFolderById(int folderId);
  Future<bool> deleteAllFolders();
  Future<bool> deleteAllFoldersHistory();
  Future<bool> resetFoldersSynchronizationTimeStamp();
  Future<bool> resetAllCountersForFolderId(int folderId);
  Future<bool> deleteAllCountersForFolderId(int folderId);
  Future<bool> deleteAllCounters();
  Future<bool> deleteAllCountersHistory();
  Future<bool> resetCountersSynchronizationTimeStamp();
  Future<Settings> getSettings();
  Future<Settings> updateSettings(Settings settings);
  Future<bool> reorderFolders(List<ReorderItem> reorderItems);
  Future<bool> reorderCounters(List<ReorderItem> reorderItems);
  Future<Statistics> addStatistics(Statistics statistics);
  Future<void> addStatisticsForFolder(int folderId, StatisticsType statisticsType);
  Future<List<Statistics>> getCounterStatistics(int counterId, DateTime start, DateTime end);
  Future<List<Statistics>> getAllStatistics();
  Future<bool> deleteAllStatistics();
  Future<int> batchInsertFolders(List<Map<String, Object?>> jsonList);
  Future<int> batchInsertCounters(List<Map<String, Object?>> jsonList);
  Future<int> batchInsertStatistics(List<Map<String, Object?>> jsonList);
}
